### ISSUE TITLE
Error al cerrar sesión con un usuario de rol artista.

### ISSUE THREAD

**Issue by DiegoTenenbaum** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#30]
Como artista, una vez iniciada la sesión, no puedo cerrarla.

![image](https://user-images.githubusercontent.com/70977407/230783116-12cf1cef-afa8-45e4-8afa-4ca9b096f973.png)
![image](https://user-images.githubusercontent.com/70977407/230783211-49e4b501-d533-4624-85db-4886b1272636.png)

**Comment by DiegoTenenbaum** [comment]
Como Artista, Quiero cerrar sesion Para que el usuario tenga  control de sus sesiones activas, seguridad y privacidad.

**Comment by mateoCosta1** [comment]
Criterio de aceptación:

**Escenario:** "Apretar el boton de cerrar sesion como artista"
*Dado* que me encuentro en el menu principal
*Y* estoy iniciado sesión como artista
*Cuando* apreto el botón de cerrar sesión
*Entonces* debería cerrarse la sesión

**Comment by DiegoTenenbaum** [comment]
Se tardo: 

Tiempo (en horas): 2 días

Esfuerzo (en horas persona): 30 minutos

**Comment by mateoCosta1** [comment]
Como se encontro el bug:

**Dado** que inicie sesión con un artista
**Cuando** apreto el boton de cerrar sesión
**Entonces** sigo viendo que me encuentro logueado
**Y** si inspecciono la pagina, observo que ocurrio un error interno
