### ISSUE TITLE
Dar baja a un género como administrador

### ISSUE THREAD

**Issue by mateoCosta1** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#6]
En el momento de listar los géneros existentes, no se cuenta con la funcionalidad de dar de baja un género.

Menu actual del administrador a la hora de administrar los géneros:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/89783683/230732707-ecdf51bd-9af1-4bc8-a9f3-cf118d0f12b3.png">

**Comment by mateoCosta1** [comment]
US:

COMO administrador
QUIERO dar de baja a un género
PARA poder eliminar a un género que no existe y fue introducido por un error

**Comment by mateoCosta1** [comment]
Criterio de aceptación:

**Escenario 1:** "Apretar el boton de eliminar género como administrador"
*Dado* que me encuentro en el menu de listado de géneros
*Y* he iniciado sesión como administrador
*Si* apreto el boton de eliminar correspondiente a un género
*Entonces* debería informarme la severidad de la acción  
     *Y* debería pedirme confirmación
     *Y* debería darme la opción de cancelar

**Escenario 1.1:** "Confirmar la eliminación de un género"
*Dado* que ejecute el escenario 1
*Si* apreto el boton de confirmar
*Entonces* debería darse de baja el género en el sistema 

**Escenario 1.2:** "Cancelar la eliminación de un género"
*Dado* que ejecute el escenario 1
*Si* apreto el boton de cancelar
*Entonces* debería volver al menu de listado de géneros
    *Y* debería estar presente el generó que intente eliminar en el escenario 1

**Comment by DiegoTenenbaum** [comment]
Se tardo: 

Tiempo (en horas): 2 días

Esfuerzo (en horas persona): 30 minutos

**Comment by mateoCosta1** [comment]
Como se encuntro el bug:

**Dado** que he iniciado sesión como administrador
**Si** voy al menu de listado de generos
**Entonces** me encuentro que solo hay un boton para editar generos, y no hay un boton para eliminarlos.
