### ISSUE TITLE
Mantenimiento de snacks

### ISSUE THREAD

**Issue by DiegoTenenbaum** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#72]
El usuario administrador puede realizar alta y baja de snacks con descripción y precio (datos obligatorios).

**User story 1)**
**Título** Alta de snack
**Como** Administrador
**Quiero** poder dar de alta un snack, ingresando descripción y precio obligatoriamente. 
Para agregarlo al sistema.

**Criterios de Aceptación:**

**Escenario 1:** Seleccionar la opción de dar de alta un snack
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de los snacks
**Cuando** apreto el boton de “Crear snack”
**Entonces** se me redirige a una pestaña de creación de snacks

**Escenario 2:** Crear un snack sin descripción
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de creación de los snacks
Y escribo un precio
**Cuando** apreto el boton de “Confirmar”
**Entonces** me sale un mensaje de error que dice “Tiene que ingresar una descripción para el snack”

**Escenario 3:** Crear un snack sin precio
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de creación de los snacks
Y escribo una descripción 
**Cuando** apreto el boton de “Confirmar”
**Entonces** me sale un mensaje de error que dice “Tiene que ingresar un precio para el snack”

**Escenario 4:** Crear un snack sin precio ni descripción
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de creación de los snacks
**Cuando** apreto el boton de “Confirmar”
**Entonces** me sale un mensaje de error que dice “Tiene que ingresar un precio y una descripción para el snack”

**Escenario 5:** Crear un snack con un precio negativo
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de creación de los snacks
Y ingrese una descripción 
Y ingese un precio negativo
**Cuando** apreto el boton de “Confirmar”
**Entonces** me sale un mensaje de error que dice “Tiene que ingresar un precio mayor o igual a 0 para el snack”

**Escenario 6:** Crear un snack con un precio positivo
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de creación de los snacks
Y ingrese una descripción 
Y ingese un precio positivo
**Cuando** apreto el boton de “Confirmar”
**Entonces** me sale un mensaje que dice “Snack creado con éxito”
Y se me redirige a la pestaña de los snacks

**Escenario 7:** Crear un snack con un descripción existente
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de creación de los snacks
Y escribo una descripción que ya existe previamente
Y escribo un precio positivo
**Cuando** apreto el boton de “Confirmar”
**Entonces** me sale un mensaje de error que dice “Snack creado previamente”

**User story 2)**
**Título** Baja de snack
**Como** Administrador
**Quiero** poder dar de baja un snack
**Para** que no esté disponible para los usuarios.

**Criterios de Aceptación:**

**Escenario 1:** Seleccionar la opción de eliminar un snack
**Dado** que me encuentro logueado como administrador
Y me encuentro en la pestaña de los snacks
**Cuando** apreto el boton que se encuentra al costado de un snack de “Eliminar snack”
**Entonces** se muestra un aviso que me informa de la severidad de la acción y me pide confirmación

**Escenario 1.1:** Apretar el botón de “Eliminar”
**Dado** que ejecute el escenario 1
**Cuando** apreto el boton de “Eliminar”
**Entonces** vuelvo a la pestaña de listado de snacks
Y el snack se eliminó del listado 
Y las personas que compraron este snack pueden consumir las unidades que compraron
Y los espectadores no pueden comprar de ahora en adelante unidades de este producto

**Escenario 1.2:** Apretar el botón de “Cancelar”
**Dado** que ejecute el escenario 1
**Cuando** apreto el boton de “Cancelar”
**Entonces** vuelvo a la pestaña de listado de snacks
Y el snack sigue estando listado

**Comment by DiegoTenenbaum** [comment]
08/05/2023 - 1h para desarrollar el front end, participantes 1 persona => tiempo de esfuerzo en horas persona = 1h.

12/05/2023 - 3h para desarrollar el back end, participantes 1 persona => tiempo de esfurzo en horas persona = 3h.

**Comment by federicocz** [comment]
Perfecto
