### ISSUE TITLE
Comprar snacks

### ISSUE THREAD

**Issue by DiegoTenenbaum** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#73]
Antes de finalizar una compra de tickets, se ofrece la posibilidad de comprar Snacks. El espectador puede agregar distintas cantidades de snacks, se calcula el subtotal de snacks y se suma al de tickets.

**User story 3)**
**Título** Compra de snacks
**Como** Espectador
**Quiero** poder comprar un snack antes de terminar mi compra de tickets
**Para** poder comer snacks mientras veo el concierto

**Criterios de Aceptación:**

**Escenario 1:** Seleccionar la opción de comprar snacks
**Dado** que realice los pasos de compra de tickets correctamente
**Cuando** apreto el boton de “Comprar tickets”
**Entonces** se muestra un menú del cual puedo seleccionar distintos snacks y distintas cantidades

**Escenario 1.1:** Seleccionar una cantidad de snacks menor o igual a 0
**Dado** que ejecute el escenario 1
Y seleccionó un conjunto (no vacío) de snacks
Y en cualquiera de los snacks seleccionó una cantidad de snacks menor o igual a 0
**Cuando** apreto el boton de “Confirmar compra de snacks”
**Entonces** se muestra un mensaje de error que dice “No se puede comprar una cantidad de snacks menor o igual a 0”

**Escenario 1.2:** No seleccionar ningún snack 
**Dado** que ejecute el escenario 1
**Cuando** apreto el boton de “Confirmar compra de snacks”
**Entonces** se muestra un mensaje de error que dice “Tiene que seleccionar al menos un snack”

**Escenario 1.3:** Cancelar la compra de snacks 
**Dado** que ejecute el escenario 1
**Cuando** apreto el boton de “Cancelar”
**Entonces** vuelvo al menu en el que me encontraba previo a la compra de snacks

**Escenario 1.4:** Cancelar la compra de snacks con snacks seleccionados
**Dado** que ejecute el escenario 1
Y seleccionó un conjunto (no vacío) de snacks
Y en los snacks seleccionó una cantidad 
**Cuando** apreto el boton de “Cancelar”
**Entonces** vuelvo al menu en el que me encontraba previo a la compra de snacks
Y no se me sumó el precio correspondiente a la cantidad seleccionada de snacks al precio total de los tickets

**Escenario 1.5:** Compra exitosa de snacks
**Dado** que ejecute el escenario 1
Y seleccionó un conjunto (no vacío) de snacks
Y seleccione una cantidad mayor a 0 para cada snack seleccionado
**Cuando** apreto el boton de “Confirmar compra de snacks”
**Entonces** vuelvo al menu en el que me encontraba previo a la compra de snacks
Y se me sumó el precio correspondiente a la cantidad seleccionada de snacks al precio total de los tickets

**Comment by DiegoTenenbaum** [comment]
10/05/2023 - 6h para arreglar las verciones de angular y otras instalaciones,participantes 1 persona => tiempo de esfuerzo en horas persona = 1h. 

10/05/2023 - 1h para desarrollar el front end, participantes 1 persona => tiempo de esfuerzo en horas persona = 1h.

10/05/2023 - 7h para desarrollar los test de spectflow y la implementacion que los haga pasar, participantes 1 persona => tiempo de esfuerzo en horas persona = 7h.

11/05/2023 - 1,5h para desarrolar la implementacion que haga pasar los test de spectflow, participantes 1 persona => tiempo de esfuerzo en horas persona = 1,5h.

12/05/2023 - 0,3h para integrar back con front, participantes 1 persona => tiempo de esfuerzo en hora persona = 0,3h.

**Comment by federicocz** [comment]
Excelente
