### ISSUE TITLE
Automatizacion de integration testing para bug/darBajaAUnGeneroComoAdministrador

### ISSUE THREAD

**Issue by mateoCosta1** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#78]
### Descripción:
En el momento de listar los géneros existentes, no se contaba con la funcionalidad de dar de baja un género.

### Escenarios:

**Escenario 1:** "Apretar el boton de eliminar género como administrador"
*Dado* que me encuentro en el menu de listado de géneros
*Y* he iniciado sesión como administrador
*Si* apreto el boton de eliminar correspondiente a un género
*Entonces* debería informarme la severidad de la acción  
     *Y* debería pedirme confirmación
     *Y* debería darme la opción de cancelar

**Escenario 1.1:** "Confirmar la eliminación de un género"
*Dado* que ejecute el escenario 1
*Si* apreto el boton de confirmar
*Entonces* debería darse de baja el género en el sistema 

**Escenario 1.2:** "Cancelar la eliminación de un género"
*Dado* que ejecute el escenario 1
*Si* apreto el boton de cancelar
*Entonces* debería volver al menu de listado de géneros
    *Y* debería estar presente el generó que intente eliminar en el escenario 1

**Comment by DiegoTenenbaum** [comment]
Entra al backlog: 19/05/2023
Se comienza a hacer hasta dejarla en PO Review: 20/05/2023
Pasa a done:
