### ISSUE TITLE
Automatizacion de integration testing para bug/errorAlCerrarSesionComoArtista

### ISSUE THREAD

**Issue by mateoCosta1** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#79]
### Descripción:
Como artista, una vez iniciada la sesión, ocurría el bug de que no podía cerrar sesión. 

### Escenarios:

**Escenario:** "Apretar el boton de cerrar sesion como artista"
_Dado_ que me encuentro en el menu principal
_Y_ he iniciado sesión como artista
_Cuando_ apreto el botón de cerrar sesión
_Entonces_ debería cerrarse la sesión

**Comment by DiegoTenenbaum** [comment]
Entra al backlog: 19/05/2023
Se comienza a hacer hasta dejarla en PO Review: 20/05/2023
Pasa a done:
