### ISSUE TITLE
Automatizacion de integration testing para feature/comprarSnacks

### ISSUE THREAD

**Issue by mateoCosta1** [mateoCosta1/Costa-Czarnievicz-Tenenbaum#80]
### Descripción:

Antes de finalizar una compra de tickets, se ofrece la posibilidad de comprar Snacks. El espectador puede agregar distintas cantidades de snacks, se calcula el subtotal de snacks y se suma al de tickets.

### Escenarios:

**Escenario 1:** Seleccionar la opción de comprar snacks
**Dado** que realice los pasos de compra de tickets correctamente
**Cuando** apreto el boton de “Comprar tickets”
**Entonces** se muestra un menú del cual puedo seleccionar distintos snacks y distintas cantidades

**Escenario 1.1:** Seleccionar una cantidad de snacks menor o igual a 0
**Dado** que ejecute el escenario 1
Y seleccionó un conjunto (no vacío) de snacks
Y en cualquiera de los snacks seleccionó una cantidad de snacks menor o igual a 0
**Cuando** apreto el boton de “Confirmar compra de snacks”
**Entonces** se muestra un mensaje de error que dice “No se puede comprar una cantidad de snacks menor o igual a 0”

**Escenario 1.2:** No seleccionar ningún snack 
**Dado** que ejecute el escenario 1
**Cuando** apreto el boton de “Confirmar compra de snacks”
**Entonces** se muestra un mensaje de error que dice “Tiene que seleccionar al menos un snack”

**Escenario 1.3:** Cancelar la compra de snacks 
**Dado** que ejecute el escenario 1
**Cuando** apreto el boton de “Cancelar”
**Entonces** vuelvo al menu en el que me encontraba previo a la compra de snacks

**Escenario 1.4:** Cancelar la compra de snacks con snacks seleccionados
**Dado** que ejecute el escenario 1
Y seleccionó un conjunto (no vacío) de snacks
Y en los snacks seleccionó una cantidad 
**Cuando** apreto el boton de “Cancelar”
**Entonces** vuelvo al menu en el que me encontraba previo a la compra de snacks
Y no se me sumó el precio correspondiente a la cantidad seleccionada de snacks al precio total de los tickets

**Escenario 1.5:** Compra exitosa de snacks
**Dado** que ejecute el escenario 1
Y seleccionó un conjunto (no vacío) de snacks
Y seleccione una cantidad mayor a 0 para cada snack seleccionado
**Cuando** apreto el boton de “Confirmar compra de snacks”
**Entonces** vuelvo al menu en el que me encontraba previo a la compra de snacks
Y se me sumó el precio correspondiente a la cantidad seleccionada de snacks al precio total de los tickets

**Comment by DiegoTenenbaum** [comment]
Entra al backlog: 19/05/2023
Se comienza a hacer hasta dejarla en PO Review: 22/05/2023
Pasa a done:
